---
title: What drives loyalty on a news website?
author: Rachit Kinger
date: '2019-07-12'
slug: what-drives-loyalty-on-a-news-website
categories:
  - data science
  - r
  - content analysis
tags:
  - nlp
  - content analysis
  - tidytext
  - network analysis
  - google autoML
subtitle: 'Using Tidytext, network analysis, Google AutoML and the works'
draft: true
---

## Summary  
XXXXXX Features of content (metadata and actual content) was used to determine whether highly loyal audience consume more of a certain type of content or not. 
IS THIS GOING TO BE A MULTI-PART SERIES?

## Context  
Websites often care about scale (number of users) and depth (amount of content). For content websites, like news publishers, balancing both is difficult. Simply speaking, scale requires one to reach more people while depth requires one to reach more people more frequently. As you can probably imagine it is not easy to achieve both. There is perhaps an argument to be made here that a strategy which achieves one struggles to achieve the other but that's for a later discussion. 

## Business objective  
It's no secret that news publishing industry is in trouble _(citation needed)_. Revenue from print both, advertising and subscription, has been steadily declining and digital advertising isn't picking up the slack. That leaves just one front, revenue from online readers; quite literally **the final frontier**. Without trying to sound like a doomsayer I do believe it is all or nothing when it comes to this battlefront with the quintessential question being, _"how can we create content and experiences that our online readers will pay for?"_  

> The quintessential questions is, 'how can we create content and experiences that our online readers will pay for?'  

Goes without saying, if we care for our readers our readers will care for us, but that's easier said than done. Let's say that while our long term goal is to reach a position where our readers pay for the content we produce, in the short to medium term we want to build depth in our readership i.e. they visit us frequently.  

### It's all about habits  
When it comes to subscription to news sites, my core belief is that people will pay for unlimited access to news if there is a habit associated with consuming that news. Sounds rather simplistic, doesn't it? So let's examine this statement a bit more in detail. I see a few obvious challenges to the statement.  

- __Challenge 1: Habit of news consumption is not the same as habit to my webiste__ Given the amount of free content available online how can one establish that the 'habit' that a publishers 'sees' on their site is specific to that site? After all, most news aggregators (Google News, Apple News, Samsung News) tend to club topics together. If a reader is interested in on the topic of 'BREXIT', then the news aggregator is likely to pepper their feed with BREXIT stories from various news sites and the reader is likely to visit more than one website.  
- __Challenge 2: Consuming freely available news is not the same as paying for news__ If anything it depends on the price. A £35 monthly subscription (FT.com) is very different from £10 monthly subscription. How elastic is your user-base's demand is a more complex question.  
















